// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompIt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CompIt'](arg1, arg2, arg3, arg4, arg5);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}
