// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompIt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function GetProgress():Promise<number>;
